name: Deploy to GitHub Pages

on:
  push:
    branches:
      - source  # Trigger the workflow on push to source branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.14.0  # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Documentation
      run: |
        cd doc
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically creates this secret to use in your workflow
        publish_dir: ./doc/_build/html  # Directory containing built docs
        publish_branch: master  # The branch you are deploying to (GitHub Pages)
